apiVersion: v1
kind: Service
metadata:
  name: contatos-add-service
spec:
  selector:
    app: contatos-add-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP
